# sonic generic ONIE image installer

SONIC_GENERIC_ONIE_IMAGE = sonic-generic.bin
$(SONIC_GENERIC_ONIE_IMAGE)_MACHINE = generic
$(SONIC_GENERIC_ONIE_IMAGE)_IMAGE_TYPE = onie
$(SONIC_GENERIC_ONIE_IMAGE)_INSTALLS = $(SYSTEMD_SONIC_GENERATOR)
$(SONIC_GENERIC_ONIE_IMAGE)_DOCKERS =
SONIC_INSTALLERS += $(SONIC_GENERIC_ONIE_IMAGE)

# sonic generic amd64 ONIE rescue live image (boots fully from RAM, no disk install)

SONIC_GENERIC_RESCUE_IMAGE = sonic-generic-rescue.bin
$(SONIC_GENERIC_RESCUE_IMAGE)_MACHINE = generic
$(SONIC_GENERIC_RESCUE_IMAGE)_IMAGE_TYPE = rescue
$(SONIC_GENERIC_RESCUE_IMAGE)_INSTALLS =
$(SONIC_GENERIC_RESCUE_IMAGE)_DOCKERS =
SONIC_INSTALLERS += $(SONIC_GENERIC_RESCUE_IMAGE)
